excid3/jumpstart

- template.rb
Update Devise to version 4.4.3.
Increase the Rails requirement version so it will work with older versions of rails than Rails 5.2 where Env Credentials are not available.
> Update Devise to latest version and add Rails 5.2 as requirement..

- template.rb
I ran into this "generate devise:install does nothing" and hangs forever issue. Added stopping spring after bundle so the generators do their job.
https://stackoverflow.com/questions/36660379/rails-generate-deviseinstall-does-nothing
> stop spring before devise generator runs

- app/views/shared/_navbar.html.erb
Fixes the wrong number of arguments error (gem font-awesome now requires the syntax to be <%= icon('fas','nameOfIcon') %>). Before this change it raises an exception (wrong number of arguments: given 1, expected 2 .. 4) when masquerading an user.
> Fix wrong number of arguments error in icon in Masquerade

- template.rb
Out of the box we cannot use our application's helpers within Administrate views.
This changes the wonderful `jumpstart` template so that our application's helpers can be used inside Administrate generated views.
> Make Application helpers accessible to Administrate

- README.md
- app/models/service.rb
- template.rb
Rails.application.secrets will soon be deprecated. Let's leverage the
new credentials way of doing things that comes with Rails 5.2 (https://github.com/rails/rails/pull/30067)
I've proposed a structure that checks the current environment - so you can have unique secrets for development and production:
```
development:
github:
app_id:
secret:
facebook:
app_id:
secret:
twitter:
app_id:
secret:
production:
github:
app_id:
secret:
facebook:
app_id:
secret:
twitter:
app_id:
secret:
```
> Use the new credentials API in Rails 5.2

- template.rb
A while ago Rails switched to `bigint` as the default primary key type: https://github.com/rails/rails/pull/26266
I noticed that the the `notifications` table is using FKs of type `integer` when the primary keys they point to are actually `bigint`s (due to the above mentioned change).
I think it's best if they are the same and here's a lame post I threw together explaining why: http://ruby.zigzo.com/2018/08/29/foreign-key-column-types/
Thanks!
> Use bigint instead of integer for reference column types

- template.rb
Hey @excid3,
I spotted a small typo in the code where the OmniAuth config would fail when setting up for each provider.
Let me know if you have questions!
> Fix a typo on the OmniAuth config

- template.rb
This patch will fix automatic generation of Omniauth links on the 'Sign Up' & 'Login' pages.
The current implementation is checking entries in `Rails.application.credentials` against an Array of Strings but the keys of the credential providers are presented as Symbols. This patch will check against an Array of Symbols
> fix omniauth link generation.

- lib/templates/erb/scaffold/show.html.erb
glyph icons are not currently in this build but were referenced in the show scaffold template.
> removed glyph icon reference

- app/views/shared/_navbar.html.erb
Updates the Fontawesome flag icon for the notifications in the navbar.
**Problem**
Notification icon does not show in the navbar.
**Solution**
Updated reference to appropriate Fontawsome icon.
> Fontawesome flag reference updated.

- CHANGELOG.md
- template.rb
Rescue errors when committing to git if `user.email` is not configured.
> Rescue from git configuration exception

- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
Howdy,
I have edited the error handling partials after removing the deprecated features from the views.
Devise is changing how error handling works in the next major version. Instead of using `<%= devise_error_messages! %>`, we are now told to use `<%= render "devise/shared/error_messages", resource: resource %>`
> Update Devise View Error Handing

- app/views/shared/_navbar.html.erb
Switched from Administrate to Madmin in
6c512b7050a369e38809ecb56f883b693b116af6 and there is no longer a path
for `admin_root_path`. Madmin uses `madmin_root_path`. Updating the
navbar to reflect that.
> Use madmin_root_path instead of admin_root_path

- test/template_test.rb
This pull request places the [APP_NAME] before the options to `rails_new` in TemplateTest.
Placing [APP_NAME] *after* options results in unexpected behaviour on some platforms.
This change is not expected to alter behaviour on unaffected platforms.
closes #136
> rearrange order of arguments to 'rails new'

- template.rb
Removed   "gem 'image_processing'" from #add_gems because it's already in the Gemfile before #add_gems is run.  Having image_processing mentioned twice in the Gemfile is causing errors.
> removed   gem 'image_processing' from #add_gems

- template.rb
Unless you're developing an Intel-based Linux machine, the first deploy to Hatchbox or Heroku will likely fail with an error such as:
```
Your bundle only supports platforms ["arm64-darwin-21"] but your local platform
is x86_64-linux. Add the current platform to the lockfile with `bundle lock
--add-platform x86_64-linux` and try again.
```
I've added a step to run the necessary `bundle` command.
I realize that if Hatchbox or Heroku move to a different architecture in future then approach this may no longer be viable.
> Add x86_64-linux as a platform for Bundler

- template.rb
Default `importmaps` used during `rails new` step and subsequent `esbuild` installation step causes errors described in #175.
This PR tickles internal `@options` overriding `javascript` option to `esbuild`. 
As a result, running `rails new myapp -d postgresql -m https://raw.githubusercontent.com/excid3/jumpstart/master/template.rb` will result in selection of `esbuild` by default.
> Fix importmap/esbuild conflict during rails new

- app/controllers/application_controller.rb
The old usage was deprecated in 2.2.0 (Feb 2022) and now emits a warning, see [changelog](https://github.com/varvet/pundit/blob/main/CHANGELOG.md).
```
DEPRECATION WARNING: 'include Pundit' is deprecated. Please use 'include Pundit::Authorization' instead.
```
> Update Pundit include

- template.rb
Re-order the instructions so that you only have to migrate once because noticed:model requires a migration.
> Re-order instructions

- Procfile.dev
- template.rb
@excid3 While working on a project this weekend with Jumpstart, I noticed that the HMR was not working. These small changes, based on my testing, should fix the problem:
- Update `Procfile.dev`
- The `chokidar` package was missing
Thanks for a great product.
> Update esbuild configuration for HMR

- esbuild.config.mjs
The previous glob was a little too restrictive and would not watch files targeted at request variants e.g. `app/views/things/show.html+phone.erb`
> Relax watchDirectories glob

- template.rb
@excid3 This removes Rails 6 installs #198 :
- Checked the method `rails_7_or_newer?` sooner so we can exit out before the install gets too far
- Included an error message and a note to delete the partial install directory
**One edge case**
We are not checking if the user overrides the default system Rails version: `rails _6.1.7_ new appname ...`.
> Update Rails version check if Rails 7 or newer is not being used.

- test/template_test.rb
I think the problem I encountered in #171 could have been caught if `yarn build` ran as part of the tests.
I've implemented this as a test following the style of the existing ones, but checking the exit code of `yarn build` may be more appropriate.
> Run `yarn build` as part of tests
